spring.application.name=o-way


# MariaDB connection
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/oway?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

# Hibernate auto-create/update tables
spring.jpa.hibernate.ddl-auto=update

# Optional: show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8000
